### ISSUE TITLE
Add mono 6.8 and msbuild 16.6 to morty

### ISSUE THREAD

**Issue by klasyc** [DynamicDevices/meta-mono#103]
Hi,

I am using EOL branch `morty` and I needed to update some recipes, namely `msbuild` to version 16.6 and `mono` to version 6.8. This operation also involves some dependencies. Now both recipes compile correctly and I would like to share my changes to the community. Please see my PR for details. This is my very first Yocto contribution, please be lenient with me...

Klasyc

**Comment by ajlennon** [comment]
I have the autobuilder going now. The build is failing. Need to work out why. It's probably related to the host build environment being too new. The older builds really don't seem to like gcc 9/10

**Comment by klasyc** [comment]
I am using Ubuntu 16.04 Docker image for my builds. Thank you for paying attention to my work :)

**Comment by ajlennon** [comment]
Merged
