### ISSUE TITLE
add dotnet 6 recipe

### ISSUE THREAD

**Issue by karthago1** [DynamicDevices/meta-mono#125]
Hello !

Second PR :) ,

I renamed dotnet_5.0.300.bb to dotnet_6.0.201.bb and changed all URLs and checksums

both dotnet versions have the same folder structure. so the install logic of dotnet 5 should be valid for dotnet 6

I tested only `arm64`.  `x64` will be soon tested
(`arm` will not be tested, but there is no reason why it shouldn't work)

it will be nice if you accept this PR

**Comment by karthago1** [comment]
sure I will try to modify the CI in the same PR

**Comment by ajlennon** [comment]
Lovely thanks

**Comment by karthago1** [comment]
hello @ajlennon 

I have to thank you too, since I learned new things like the yocto imagetest.
it is still work in progress. I will write here as soon as I finished it.

**Comment by karthago1** [comment]
@ajlennon

as I said I just added an insane skip to ignore the lttng-ust dependency. I think it is safe to do it for now. but we should remove it as soon as dotnet runtime switches to use the new lib.

for now I have a problem with dotnet-helloworld_1.0.bb. to compile the source code, the command `dotnet build` is executed, which needs to access this url https://api.nuget.org/v3/index.json.

the command is working fine in my environment (with your docker image). but the CI seems to have no access to that file. may be you have an idea, what is going wrong?

`/__w/meta-mono/meta-mono/master/build/tmp/work/core2-64-poky-linux/dotnet-helloworld/1.0-r0/recipe-sysroot-native/usr/share/dotnet/sdk/6.0.201/NuGet.targets(130,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/__w/meta-mono/meta-mono/master/build/tmp/work/core2-64-poky-linux/dotnet-helloworld/1.0-r0/src/dotnet-helloworld.csproj]`

**Comment by ajlennon** [comment]
I tried that myself but then the rootfs failed to build for some reason?
