### ISSUE TITLE
QA Issue: /usr/lib/mono/4.5/Microsoft.CodeAnalysis.Scripting.dll contained in package mono-libs-4.5 requires mono(System.Runtime.Loader), but no providers found in RDEPENDS_mono-libs-4.5

### ISSUE THREAD

**Issue by sheraz045** [DynamicDevices/meta-mono#15]
ERROR: mono-5.14.0.177-r0 do_package_qa: QA Issue: /usr/lib/mono/4.5/Microsoft.CodeAnalysis.Scripting.dll contained in package mono-libs-4.5 requires mono(System.Runtime.Loader), but no providers found in RDEPENDS_mono-libs-4.5? [file-rdeps]
ERROR: mono-5.14.0.177-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: mono-5.14.0.177-r0 do_package_qa: Function failed: do_package_qa

I'm on Ubuntu 16.04LTS

$ bitbake -e virtual/kernel | grep "^PV="
PV="4.14.98"

$ bitbake --version
BitBake Build Tool Core version 1.38.0

meta-mono            = "master:1a54dbe8027644e68b02f4e44ca2f631d7e80e99"

**Comment by ajlennon** [comment]
Is this still an issue?

**Comment by ajlennon** [comment]
No response so closing issue
