### ISSUE TITLE
mono_6.12.0.107 QA Issue in Yocto gatesgarth

### ISSUE THREAD

**Issue by VladimirSazonov** [DynamicDevices/meta-mono#91]
Hello.
I was trying to build mono_6.12.0.107 for yocto "gatesgarth". Everything went fine, but QA gave the following error messages:

ERROR: mono-6.12.0.107-r0 do_package_qa: QA Issue: /usr/lib/libMonoPosixHelper.so contained in package mono-libs requires libz.so.1()(64bit), but no providers found in RDEPENDS_mono-libs? [file-rdeps]
ERROR: mono-6.12.0.107-r0 do_package_qa: QA Issue: /usr/bin/monodis contained in package mono-dev requires libz.so.1()(64bit), but no providers found in RDEPENDS_mono-dev? [file-rdeps]
ERROR: mono-6.12.0.107-r0 do_package_qa: QA Issue: /usr/lib/libmonosgen-2.0.so.1.0.0 contained in package mono requires libz.so.1()(64bit), but no providers found in RDEPENDS_mono? [file-rdeps]
ERROR: mono-6.12.0.107-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

Everything is fine in the "warrior" version, there are no messages. Don't understand which package is supposed to provide the libz.so.1 () (64bit) library? The zlib and zlib-intel packages are present.

**Comment by ajlennon** [comment]
gatesgarth is building so closing this
